name: firebase_common
description: MOTTAI app firebase common.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutterfire_gen_annotation: ^0.1.0-dev.3
  # flutterfire_gen_ts_annotation: ^0.0.1-dev.1
  flutterfire_gen_utils: ^0.0.1-dev.3
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutterfire_gen: ^0.0.1-dev.8
  # flutterfire_gen_ts: ^0.0.1-dev.1

flutter:
  uses-material-design: true
