name: mottai_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=3.0.3'

dependencies:
  cached_network_image:
  cloud_firestore: ^3.4.3
  cloud_functions: ^3.3.3
  connectivity_plus:
  crypto:
  cupertino_icons:
  firebase_analytics: ^9.3.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_keyboard_visibility:
  flutter_line_sdk:
  flutter_localizations:
    sdk: flutter
  flutter_native_image:
  flutter_signin_button:
  flutter_spinkit:
  flutter_state_notifier:
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  gap:
  geoflutterfire:
    path: ../geoflutterfire
  geolocator:
  google_fonts:
  google_maps_flutter:
  google_sign_in:
  hooks_riverpod:
  image_cropper:
  image_picker:
  intl:
  json_annotation:
  keyboard_actions:
  mottai_flutter_app_models:
    path: ../models
  package_info_plus: ^1.4.3
  path_to_regexp: ^0.4.0
  photo_view:
  rxdart:
  shared_preferences:
  shimmer: ^2.0.0
  sign_in_with_apple:
  state_notifier:
  tuple: ^2.0.0
  url_launcher:
  uuid:
  wechat_assets_picker:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  pedantic_mono:

dependency_overrides:
  hooks_riverpod: '>=2.0.0-0'

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher_icon/launcher_icon.png'
